### ISSUE TITLE
Add category dropdown to feedback form

### ISSUE THREAD

**Issue by JoeAyre** [mvdungen/SPFx-Extension-Feedback#6]
Hi,

Firstly, I really like your feedback solution - it's very slick.
Secondly, this isn't really an issue - more an idea/extension to the solution - apologies, I wasn't sure how to add an 'idea/suggestion', or label this 'issue' accordingly.

I've taken some great ideas from it and wonder if you would have any idea how I could incorporate a dropdown category field on the feedback form to allow users to select a category of feedback e.g. eneral, typo, incorrect content, inappropriate content.
I've got as far as modifying the solution to get the CreateListForm.tsx to create the new column for 'Feedback Category', but am struggling to actually add a dropdown menu to the FeedbackForm.tsx to a) display the static options and b) write the selected option to the new list column.
If you could give me any pointers that would be great.
Thanks

**Comment by mvdungen** [comment]
Hi Joe, I think there are several options to accomplish this. My advice would be not to incorporate the choices in the solution itself. If you do, you are always stuck to these options. A better approach would be to create (as you did) the field in `CreateListForm.tsx`. Once the list is created, you can add the options in the list itself.

When opening the feedback form, you could retrieve the list field and retrieve the choices, and showing them on the form. You can take a look at [@pnp/sp/fields](https://pnp.github.io/pnpjs/sp/fields/) how to retrieve fields from a list. Basically, you can show the choices with a [normal Fluid Dropdown list field](https://developer.microsoft.com/en-us/fluentui#/controls/web/dropdown).

By using this approach, you are always in control what choices people see and can choose from.

**Comment by JoeAyre** [comment]
Hi @mvdungen - thanks for the tips - I'll have a look and see if I can get that working. One other thing, do you know if it is possible to push all submitted feedback to one list? I've got multiple site collections and rather than creating a list in each site collection (and configuring it), it would be great if all feedback was added to one centralised list. Not sure what I would need to change so would appreciate any pointers.

**Comment by mvdungen** [comment]
Hi @JoeAyre, I took the liberty to implement a new version with your "Category" question in the back of my mind. Implemented it in V3.0. You can either use your version or take my pre-compiled V3.0 version in the SharePoint folder. Please refer to the README to see other changes. Didn't look at the global one, there is an issue for that one, but not going to implement that feature on short notice...
